services:
    anime_db.world_art.filler:
        class: AnimeDb\Bundle\WorldArtFillerBundle\Service\Filler
        arguments: [ @anime_db.world_art.browser, @doctrine, @anime_db.downloader ]
        tags:
            - { name: anime_db.filler }
        calls:
            - [setRouter, ['@router']]

    anime_db.world_art.refiller:
        class: AnimeDb\Bundle\WorldArtFillerBundle\Service\Refiller
        arguments: [ @anime_db.world_art.filler, @anime_db.world_art.search, @anime_db.world_art.browser ]
        tags:
            - { name: anime_db.refiller }

    anime_db.world_art.search:
        class: AnimeDb\Bundle\WorldArtFillerBundle\Service\Search
        arguments: [ @anime_db.world_art.browser ]
        tags:
            - { name: anime_db.search }
        calls:
            - [setRouter, ['@router']]
            - [setFiller, ['@anime_db.world_art.filler']]

    anime_db.world_art.browser:
        class: AnimeDb\Bundle\WorldArtFillerBundle\Service\Browser
        arguments:
            - %anime_db.world_art.browser.host%
            - %anime_db.world_art.browser.timeout%
            - %anime_db.world_art.browser.proxy%
        calls:
            - [setRequest, ['@?request=']]

    anime_db.world_art.listener.refiller:
        class: AnimeDb\Bundle\WorldArtFillerBundle\Event\Listener\Refiller
        arguments: [ @event_dispatcher, @anime_db.world_art.refiller, @anime_db.world_art.filler ]
        tags:
            - { name: kernel.event_listener, event: anime_db.storage.add_new_item, method: onAddNewItem }
