services:
    anime_db.world_art.filler:
        class: AnimeDb\Bundle\WorldArtFillerBundle\Service\Filler
        arguments: [@buzz.browser, @doctrine, @validator]
        tags:
            -  { name: anime_db.filler }
        calls:
            - [setRequest, ['@?request=']]
    anime_db.world_art.search:
        class: AnimeDb\Bundle\WorldArtFillerBundle\Service\Search
        arguments: [@buzz.browser, @router]
        tags:
            -  { name: anime_db.search }
        calls:
            - [setRequest, ['@?request=']]

    # cURL client for Buzz
    buzz.client.curl:
        class:  Buzz\Client\Curl
        public: false
        calls:
            - [ setVerifyPeer, [ false ] ]
    # Buzz browser
    buzz.browser:
        class:     Buzz\Browser
        arguments: [ @buzz.client.curl ]